openapi: 3.0.3
info:
  title: Client Manager
  version: 1.0.0
  description: APIs to manage client to access IDP Provider

contact:
    name: Mateus Lima Fonseca
    email: mateuslima90@gmail.com

servers:
  - url: http://localhost:8080/api/v1/idp
    description: Production Server
  - url: http://localhost:8081/api/v1/idp
    description: UAT Server
  - url: http://localhost:8082/api/v1/idp
    description: TST Server
  - url: http://localhost:8083/api/v1/idp
    description: DEV Server
      
paths:
  /clients:
    get:
      tags:
        - clients
      summary: Return a list of clients
      descripton: Return all clients from IDP Provider
      operationId: getAllClient
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A JSON array of clients
          content:  
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        '400':
          description: Not Found
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
        '401':
          description: Unauthorized
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
        '500':
          description: Internal Server Error
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
           
  /client:
   post:
     tags:
       - clients
     summary: Create a client
     descripton: Return a specific client
     operationId: createSingleClient
     security:
       - BearerAuth: []
     requestBody:
       required: true
       content:
         application/json:
           schema:
             type: object
             properties:
                id:
                  type: string
                  example: ae1271te127ts178t27e1
                username:
                  type: string
                  example: integration-notification-api
                description:
                  type: string
                  example: Integration Notification API
                owner:
                  type: string
                  example: mateuslima90@gmail.com
                team:
                  type: string
                  example: APi Automation Team
     responses:
       '201':
         description: A JSON array of clients
         content:  
           application/json:
             schema:
              $ref: '#/components/schemas/Client'
       '400':
         description: Invalid Payload
         content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
       '409':
         description: Client already exists
         content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
       '500':
         description: Internal Server Error
         content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
       
  /client/{clientId}:
      get:
        tags:
          - clients
        summary: Search Client by Id
        descripton: Return a specific client
        operationId: getSingleClient
        security:
          - BearerAuth: []
        responses:
          '200':
            description: A JSON array of clients
            content:  
              application/json:
                schema:
                  $ref: '#/components/schemas/Client'
          '404':
            description: Not Found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
          '500':
            description: Internal Server Error          
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
        
      put:
        tags:
          - clients
        summary: Update Client by Id
        descripton: Update a specific client
        operationId: updateSingleClient
        security:
          - BearerAuth: []
        requestBody:
          required: true
          content:
           application/json:
             schema:
               type: object
               properties:
                username:
                  type: string
                  example: integration-notification-api
                description:
                  type: string
                  example: Integration Notification API
                owner:
                  type: string
                  example: mateuslima90@gmail.com
                team:
                  type: string
                  example: APi Automation Team
        responses:
          '200':
            description: A JSON array of clients
            content:  
              application/json:
                schema:
                  $ref: '#/components/schemas/Client'
          '400':
            description: Invalid Payload
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
          '404':
            description: Not Found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
          '409':
            description: Client already exists
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
          '500':
            description: Internal Server Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
      
      delete:
        tags:
          - clients
        summary: Delete Client by Id
        descripton: Delete a specific client
        operationId: deleteSingleClient
        security:
          - BearerAuth: []
        responses:
          '200':
            description: A JSON array of clients
            content:  
              application/json:
                schema:
                  $ref: '#/components/schemas/Client'
          '404':
            description: Not Found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'
          '500':
            description: Internal Server Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponse'        
      
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Client:
      x-swagger-router-model: io.swagger.petstore.model.User
      properties:
        id:
          type: string
          example: 121dasda212e12dsawd3
        username:
          type: string
          example: agLAl0hgqNKwp9APtAW6
        description:
          type: string
          example: User responsible to create bulk crm tasks
        owner:
          type: string
          example: mateuslima90@gmail.com
        team:
          type: string
          example: APi Automation Team
      xml:
        name: user
      type: object
    ApiResponse:
     x-swagger-router-model: io.swagger.petstore.model.ApiResponse
     properties:
        code:
          type: integer
          format: int64
          example: 404
        msg:
          type: string
          example: agLAl0hgqNKwp9APtAW6
     xml:
       name: ApiResponse
     type: object

