openapi: 3.0.3
info:
  title: Client Manager
  version: 1.0.0
  description: APIs to manage client to access IDP Provider

servers:
  - url: http://localhost:8080/api/v1/idp
    description: Production Server
  - url: http://localhost:8081/api/v1/idp
    description: UAT Server

basepath: 
      
paths:
  /clients:
    get:
      tags:
        - clients
      summary: Return a list of clients
      descripton: Return all clients from IDP Provider
      responses:
        '200':
          description: A JSON array of clients
          content:  
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: 
                  type: string
                  
  /client:
   post:
     tags:
       - clients
     summary: Create a client
     descripton: Return a specific client
     responses:
       '201':
         description: A JSON array of clients
         content:  
           application/json:
             schema:
              $ref: '#/components/schemas/Client'
       '409':
          description: Client already exists
                  
  /client/{clientId}:
      get:
        tags:
          - clients
        summary: Search Client by Id
        descripton: Return a specific client
        responses:
          '200':
            description: A JSON array of clients
            content:  
              application/json:
                schema:
                  $ref: '#/components/schemas/Client'
      
      put:
        tags:
          - clients
        summary: Update Client by Id
        descripton: Return a specific client
        responses:
          '200':
            description: A JSON array of clients
            content:  
              application/json:
                schema:
                  $ref: '#/components/schemas/Client'
      
      delete:
        tags:
          - clients
        summary: Update Client by Id
        descripton: Return a specific client
        responses:
          '200':
            description: A JSON array of clients
            content:  
              application/json:
                schema:
                  $ref: '#/components/schemas/Client'
                            
components:
  schemas:
    Client:
      x-swagger-router-model: io.swagger.petstore.model.User
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: agLAl0hgqNKwp9APtAW6
        description:
          type: string
          example: User responsible to create bulk crm tasks
        owner:
          type: string
          example: mateuslima90@gmail.com
        team:
          type: string
          example: APi Automation Team
      xml:
        name: user
      type: object
