/*
 * Client Manager
 * APIs to manage client to access IDP Provider
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mateuslima90@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Client;
import org.openapitools.client.model.InlineObject;
import org.openapitools.client.model.InlineObject1;
import org.openapitools.client.model.ModelApiResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientsApi
 */
@Ignore
public class ClientsApiTest {

    private final ClientsApi api = new ClientsApi();

    
    /**
     * Create a client
     *
     * Return a specific client
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSingleClientTest() throws ApiException {
        InlineObject inlineObject = null;
        Client response = api.createSingleClient(inlineObject);

        // TODO: test validations
    }
    
    /**
     * Delete Client by Id
     *
     * Delete a specific client
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSingleClientTest() throws ApiException {
        String clientId = null;
        Client response = api.deleteSingleClient(clientId);

        // TODO: test validations
    }
    
    /**
     * Return a list of clients
     *
     * Return all clients from IDP Provider
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllClientTest() throws ApiException {
        List<Client> response = api.getAllClient();

        // TODO: test validations
    }
    
    /**
     * Search Client by Id
     *
     * Return a specific client
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSingleClientTest() throws ApiException {
        String clientId = null;
        Client response = api.getSingleClient(clientId);

        // TODO: test validations
    }
    
    /**
     * Update Client by Id
     *
     * Update a specific client
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleClientTest() throws ApiException {
        String clientId = null;
        InlineObject1 inlineObject1 = null;
        Client response = api.updateSingleClient(clientId, inlineObject1);

        // TODO: test validations
    }
    
}
