# key cloack ou gluu ou algum outro IDP compativel com OAuth e OpenID Connect
# kong api gateway
# kong map
# prometheus
# pact broker
version: '3.8'
services:
  sonarqube:
    image: sonarqube:8.2-community
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  redis:
    restart: on-failure
    image: 'bitnami/redis:latest'
    networks:
      - backend
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  dbdata:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
networks:
  backend: